version: "3.7"

services:
  product:
    build:
      context: ./product
    ports:
      - 50051:50051
    restart: on-failure

  graphql:
    build:
      context: ./graphql
    ports:
      - 8080:8080
    depends_on:
      - product
    environment:
      PRODUCT_HOST: product
    restart: on-failure
